config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :restaurants do
    resources :reviews
  end

  root 'restaurants#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present? && user.admin
      can :manage, Category
      can :manage, Restaurant
      can :manage, Review
    else
      can :read, :all
      can :edit, :all
    end
    # Define abilities for the passed in user here. For example:
    #
   # user ||= User.new # guest user (not logged in)
     #if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :resturants
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category
  validates :name, presence: true
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected
  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || categories_path || root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  def update
    if @category.update_attributes(category_params)
      flash[:success] = 'Updated Successfully'
      redirect_to categories_path
    else
      flash.now[:error] = @category.errors.full_messages.to_sentence
      render :edit
    end
  end

  def create
    if @category.save
      flash[:success] = 'Created Successfully'
      redirect_to categories_path
    else
      flash.now[:error] = @category.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
 load_and_authorize_resource

def review
  if @restaurant.update_attributes(restaurant_params)
    flash[:success] = 'Reviewed Successfully'
    redirect_to restaurant_path
  else
    flash.now[:error]= @restaurant.errors.full_messages.to_sentence
    render :edit
  end
  end

  def create
    if @restaurant.save
      flash[:success]= 'Created Successfuly'
      redirect_to restaurants_path
    else
      flash.now[:error]= @restaurant.errors.full_messages.to_sentence
      render :new
    end

def comments
  @restaurant= Restaurant.find(params[:id])
  if @restaurant.update_attributes(params[:name])
    render 'reviews/new.html.haml'
  else
render :edit
  end
end
  end

    def restaurant_params
      params.require(:restaurant).permit(:name)
    end
def edit
end


def show
end

 def destroy
    if @restaurant.destroy
      flash[:success] = 'Deleted Successfuly'
      redirect_to restaurant_path
    else
      flash.now[:error]= @restaurant.error.full_messages.to_sentence
      render:delete
    end
  end


def new
  @restaurant= Restaurant.find(params[:id])
  if @restaurant.update_attributes(params[:name])
    render 'restaurants/index.html.haml'
  else
    render :edit
  end
end

  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource :restaurant
  load_and_authorize_resource

  def create
    if @review.save
       flash[:success]= 'Created Successfuly'
      redirect_to restaurants_path
    else
      flash.now[:error]= @restaurant.errors.full_messages.to_sentence
      render :new
  end
  end

  def update
    if @review.update_attributes(review_params)
    flash[:success] = 'Reviewed Successfully'
    redirect_to restaurant_path
  else
    flash.now[:error]= @restaurant.errors.full_messages.to_sentence
    render :edit
  end
  end

  def destroy
    if @review.destroy
      flash[:success] = 'Deleted Successfuly'
      redirect_to review_path
    else
      flash.now[:error]= @review.error.full_messages.to_sentence
      render:delete
    end
  end


  private
  def review_params
    params.require(:review).permit(:description, :star).merge(user_id: current_user.id, restaurant_id: @restaurant.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/controllername_helper.rb
module ControllernameHelper
end

app/helpers/resturant_helper.rb
module ResturantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/categories/_form.haml
= form_for @category, html: { class: 'form form-horizontal' } do |f|
  .form-group
    = f.label :name, 'Name', class: 'control-label col-xs-2'
    .col-xs-10
      = f.text_field :name, class: 'form-control'

  .form-group
    .col-xs-12
      = f.submit class: 'btn btn-default pull-left'

      </br>
      </br>
      -# %a{ href: restaurants_path} View Restaurants for each Category

app/views/categories/edit.haml
= render partial: 'form'

app/views/categories/index.haml
%table.table.table-condensed.table-striped.table-bordered
  %tr
    %th Name
    %th Created at
    %th Show
  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.created_at
      %td= link_to 'Edit', edit_category_path(category)
%a{ href: restaurants_path} View Restaurants for each Category

app/views/categories/new.haml
= render partial: 'form'

app/views/categories/restaurant.haml
=render partial :'form'

app/views/layouts/application.haml
!!!
%html
  %head
    %title Blog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css", :integrity => "sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1", :rel => "stylesheet"}/

%body
  - if current_user.present?
    %a{ href: destroy_user_session_path, method: :delete } logout
  - else
    = link_to 'login', new_user_session_path

-# <ul class="hmenu">
-#   <%= render 'devise/menu/registration_items' %>
-#     <%= render 'devise/menu/login_items' %>
-#     </ul>
-#     <%= yield %>
-#
-#     ul.hmenu {
-#       list-style: none;none
-#         margin: 0 0 2em;
-#           padding: 0;
-#           }
-#
-#           ul.hmenu li {
-#             display: inline;
-#             }
-#


 
  
  .container
    = yield
.container
  = yield

app/views/restaurants/index.html.haml
%table.table.table-condensed.table-striped.table-bordered
  %tr
    %th Name
    %th Category
    %th Reviews
  - @restaurants.each do |restaurant|
    %tr
      %td= restaurant.name
      %td= restaurant.category.name
      %td
        %strong
          %p Give Us Your Review about the Restaurant
        -# %button.btn.btn-success{:type => "button"} Write Reviews

        .container.row.col-md-4
          .row
          .col-md-6
        %hr/
        - restaurant.reviews.each do |review|
          .row
            .col-md-6
              %p= review.description
            .col-md-6.text-warning
              - (0...review.star.to_i).each do |s|
                %i.fa.fa-star
        %hr/
        .row.pt-3
          .col-md-12
            %a{ href: new_restaurant_review_path(restaurant) } New Review
      .col-md-8.my-5.py-5

%a{ href: categories_path } view categories

app/views/restaurants/index2.html.haml
%table.table.table-condensed.table-striped.table-bordered
  %tr
    %th Name
    %th Created at
    %th Show
  - @restaurants.each do |restaurant|
    %tr
      %td= restaurant.name
      %td= restaurant.created_at
      %td= link_to 'Edit', edit_restaurant_path(restaurant)

app/views/reviews/new.html.haml
= form_for [@restaurant, @review], html: { class: 'from form-horizontal'} do |f|
  .form-group
    = f.label :description, 'Description', class: 'control-label col-xs-2'
    .col-xs-10
      =f.text_field :description, class: 'form-control'


  .form-group
    .col-xs-12
      = f.submit class: 'btn btn-default pull-right'
      .form-group
        .col-xs-14
          = f.label :star, 'Give it a star', class: 'control-label col-xs-2'
          = f.select :star, ['1', '2','3', '4']
          </br>
          </br>
          </br>
          %a{ href: new_restaurant_review_path(@restaurant) } Write Another Review
          </br>
          %a{ href: restaurants_path} view restaurants